apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-db
  name: my-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
status: {}
