apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-db
  name: my-db
spec:
  storageClassName: regionalpd-storageclass
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: development
    name: my-db-pvc
  gcePersistentDisk:
    pdName: my-db-production
    fsType: ext4
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-db-pvc
  name: my-db-pvc
spec:
  storageClassName: regionalpd-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
status: {}
