version: "3.7"
services:
  metapub:
    container_name: metapub
    restart: always
    image: jandresh/metapub:latest
    ports:
      - "5000:5000"
    networks:
      - pipeline
networks:
  pipeline:
    name: custompipeline
    driver: bridge
