version: "3.7"
services:
  arxiv:
    build: ./app
    ports:
      - "5005:5000"
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
volumes:
  core-pv: null
