apiVersion: v1
kind: Service
metadata:
  labels:
    service: core
  name: core
spec:
  type: LoadBalancer
  ports:
    - name: "5003"
      port: 5000
      targetPort: 5000
  selector:
    service: core
status: {}
