version: "3.7"
services:
  app:
    image: jandresh/mysqlws:latest
    links:
      - db
    ports:
      - "5001:5000"
    networks: 
      - pipeline
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./../db:/var/lib/mysql
    networks: 
      - pipeline
networks: 
  pipeline:
    external: true
    name: custompipeline
