# Basado en https://github.com/stavshamir/docker-tutorial
version: "2"
services:
  app:
    image: jandresh/mysqlws:latest
    links:
      - db
    ports:
      - "5001:5000"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./../db:/docker-entrypoint-initdb.d/:ro
