apiVersion: v1
kind: Service
metadata:
  labels:
    service: arxiv
  name: arxiv
spec:
  type: ClusterIP
  ports:
    - name: "5005"
      port: 5000
      targetPort: 5000
  selector:
    service: arxiv
status: {}
