apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      service: orchestrator
  strategy: {}
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: orchestrator
    spec:
      containers:
        - image: jandresh/orchestrator:latest
          name: orchestrator
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
