version: "3.7"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    networks: 
      - pipeline
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks: 
      - pipeline
networks: 
  pipeline:
    external: true
    name: custompipeline