version: "3.7"
services:
  preprocessing:
    image: jandresh/preprocessing:latest
    ports:
      - "5002:5000"
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
