apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: preprocessing
  name: preprocessing
spec:
  replicas: 1
  selector:
    matchLabels:
      service: preprocessing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: preprocessing
    spec:
      containers:
        - image: jandresh/preprocessing:latest
          name: preprocessing
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: OnFailure
status: {}
