apiVersion: v1
kind: Service
metadata:
  labels:
    service: metapubws
  name: metapubws
spec:
  type: ClusterIP
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    service: metapubws
