version: "3.7"
services:
  orchestrator:
    image: jandresh/orchestrator:latest
    ports:
      - "5004:5000"
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
