version: "3.7"
services:
  db:
    build: ./app
    links:
      - mongo
    ports:
      - "5001:5000"
    networks:
      - pipeline
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'adccali'
      MONGO_INITDB_ROOT_PASSWORD: 'adccali'
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - pipeline
networks:
  pipeline:
    external: true
    name: custompipeline
volumes:
  mongo-db: null
