apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: core
  name: core
spec:
  replicas: 1
  selector:
    matchLabels:
      service: core
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: core
    spec:
      containers:
        - image: jandresh/core:latest
          name: core
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
