apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: arxiv
  name: arxiv
spec:
  replicas: 1
  selector:
    matchLabels:
      service: arxiv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: arxiv
    spec:
      containers:
        - image: jandresh/arxiv:latest
          name: arxiv
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: OnFailure
status: {}
