version: "3.7"
services:
  gui:
    container_name: gui
    build: jandresh/gui:latest
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - pipeline
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
networks:
  pipeline:
    external: true
    name: custompipeline
