apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: metapub
  name: metapub
spec:
  replicas: 1
  selector:
    matchLabels:
      service: metapub
  strategy: {}
  template:
    metadata:
      labels:
        network/custompipeline: "true"
        service: metapub
    spec:
      containers:
        - image: jandresh/metapub:latest
          name: metapub
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
