apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5000
      targetPort: 5000
  selector:
    service: db
status: {}
