pipeline {
    agent any
    stages {
        stage('Build metapubws') {
            steps {
                echo "Deploy metapubws test environment"
                build 'metapubws'
                echo "metapub deployed successfuly"
            }
        }
        stage('Build mysqlws') {
            steps {
                echo "Deploy mysqlws test environment"
                build 'mysqlws'
                echo "mysqlws deployed successfuly"
            }
        }
        stage('Test') {
            steps {
                // sh 'python --version'
                sh 'echo "Success!"; exit 0'
            }
        }
        stage('Publish') {
            steps {
                build 'containerPublish'
                echo "Container push to DockerHub"
            }
        }
        stage('Deploy prod') {
            steps {
                /*
                retry(3) {
                    sh 'chmod 777 deploy.sh'
                    sh './deploy.sh'
                }

                timeout(time: 3, unit: 'MINUTES') {
                    sh 'chmod 777 health-check.sh'
                    sh './health-check.sh'
                }
                */
                build 'composeDeploy'
                echo 'Success on docker-compose deployment'
                build 'ontopws'
                echo "ontopws deployed successfuly"
            }
        }
    }
    post {
        always {
            echo 'This will always run'
        }
        success {
            echo 'This will run only if successful'
        }
        failure {
            echo 'This will run only if failed'
        }
        unstable {
            echo 'This will run only if the run was marked as unstable'
        }
        changed {
            echo 'This will run only if the state of the Pipeline has changed'
            echo 'For example, if the Pipeline was previously failing but is now successful'
        }
    }
}